/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JFrameVehiculo extends javax.swing.JFrame {
    
DefaultTableModel modelo;
   
public JFrameVehiculo() {
    initComponents();
    modelo = new DefaultTableModel();
    modelo.addColumn("PLACA");
    modelo.addColumn("MARCA");
    modelo.addColumn("MODELO");
    modelo.addColumn("FRENOS");
    modelo.addColumn("PINTAR");
    modelo.addColumn("MOTOR");

this.tabla.setModel(modelo);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        botones = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PLACA = new javax.swing.JTextField();
        MARCA = new javax.swing.JTextField();
        PINTAR = new javax.swing.JComboBox<>();
        GUARDAR = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        eliminartodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MODELO = new javax.swing.JTextField();
        MOSTRAR = new javax.swing.JButton();
        MOTOR = new javax.swing.JComboBox<>();
        FRENO = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botones.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MECANICOS");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel2.setText("PLACA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel3.setText("ARREGLAR FRENOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel5.setText("PINTAR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel6.setText("MODELO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(PLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));

        MARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MARCAActionPerformed(evt);
            }
        });
        jPanel1.add(MARCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, -1));

        PINTAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEGRO", "BLANCO", "AZUL", "ROJO", "VERDE", "NO" }));
        PINTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINTARActionPerformed(evt);
            }
        });
        jPanel1.add(PINTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 190, -1));

        GUARDAR.setBackground(new java.awt.Color(0, 255, 255));
        GUARDAR.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        GUARDAR.setForeground(new java.awt.Color(0, 0, 102));
        GUARDAR.setText("GUARDAR");
        GUARDAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        jPanel1.add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 110, 40));

        eliminar.setBackground(new java.awt.Color(255, 153, 0));
        eliminar.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(0, 0, 102));
        eliminar.setText("ELIMINAR");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 220, 140, -1));

        eliminartodo.setBackground(new java.awt.Color(255, 51, 51));
        eliminartodo.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        eliminartodo.setForeground(new java.awt.Color(0, 0, 102));
        eliminartodo.setText("ELIMINAR TODO");
        eliminartodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminartodoActionPerformed(evt);
            }
        });
        jPanel1.add(eliminartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "MARCA", "MODELO", "EDAD", "PINTAR", "MOTOR"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1020, 570));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel4.setText("MARCA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel8.setText("ARREGLAR MOTOR");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        MODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODELOActionPerformed(evt);
            }
        });
        jPanel1.add(MODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 190, -1));

        MOSTRAR.setBackground(new java.awt.Color(0, 255, 255));
        MOSTRAR.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        MOSTRAR.setForeground(new java.awt.Color(0, 0, 102));
        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });
        jPanel1.add(MOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 110, 40));

        MOTOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        MOTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOTORActionPerformed(evt);
            }
        });
        jPanel1.add(MOTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 190, -1));

        FRENO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        FRENO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRENOActionPerformed(evt);
            }
        });
        jPanel1.add(FRENO, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminartodoActionPerformed
        int fila=tabla.getRowCount();
        for(int i=fila-1; i>=0; i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_eliminartodoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila=tabla.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);
        }
        else{
            JOptionPane.showMessageDialog(null,"seleccione la fila para eliminar");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        
        String placa = PLACA.getText();
        String marca = MARCA.getText();
        String modelo = MODELO.getText();
        String freno = FRENO.getSelectedItem().toString();
        String pintar = PINTAR.getSelectedItem().toString();
        String motor = MOTOR.getSelectedItem().toString();

        if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty()) {
            // Mostrar un mensaje de error si algún campo está vacío
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método sin guardar los datos
        }
       
        
        // Crear una cadena con los datos a guardar
        String datos = placa + "," + marca + "," + modelo + "," + freno + "," + pintar +","+motor;
        
        int frenod=0;
        int pintard=0;
        int motord=0;
        int total=0;
        
        if(freno!="NO"){
            frenod=30000;
            total=total+frenod;
        }
        if(pintar!="NO"){
            pintard=50000;
            total=total+pintard;
        }
        if(motor!="NO"){
            motord=250000;
            total=total+motord;
        }
        
        String datosfac = placa + "," + frenod + "," + pintard +","+motord+","+total;


        // Ruta del archivo donde se guardará la información
        String archivo = "vehiculos.txt";
        String archivofac = "factura.txt";

        try {
            // Crear un BufferedWriter para escribir en el archivo
            BufferedWriter writer = new BufferedWriter(new FileWriter(archivo, true));
            BufferedWriter writerfac = new BufferedWriter(new FileWriter(archivofac, true));


            // Escribir los datos en el archivo
            writer.write(datos);
            writer.newLine();
            
            writer.close();
            
            writerfac.write(datosfac);
            writerfac.newLine();

            // Cerrar el BufferedWriter
            writerfac.close();

            // Limpiar los campos de texto y restablecer los valores por defecto
            PLACA.setText("");
            MARCA.setText("");
            FRENO.setSelectedIndex(0);
            PINTAR.setSelectedIndex(0);
            MODELO.setText("");
            MOTOR.setSelectedIndex(0);
            
            // Mostrar un mensaje de éxito
            System.out.println("La información se ha guardado correctamente en el archivo.");
        } catch (IOException e) {
            // Mostrar un mensaje de error en caso de excepción
            System.out.println("Error al guardar la información en el archivo: " + e.getMessage());
        }
       

    }//GEN-LAST:event_GUARDARActionPerformed

    private void PINTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINTARActionPerformed

    private void MARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MARCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MARCAActionPerformed

    private void MODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODELOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODELOActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
         // Limpiar la tabla antes de mostrar los datos
    modelo.setRowCount(0);

    // Ruta del archivo donde se encuentra la información
    String archivo = "vehiculos.txt";

    try {
        // Leer el archivo y mostrar los datos en la tabla
        java.nio.file.Path path = java.nio.file.Paths.get(archivo);
        java.util.List<String> lines = java.nio.file.Files.readAllLines(path);

        for (String line : lines) {
            String[] datos = line.split(",");

            if (datos.length == 6) {
                modelo.addRow(datos);
            }
        }

        // Mostrar un mensaje de éxito
        System.out.println("Datos cargados correctamente desde el archivo.");
    } catch (IOException e) {
        // Mostrar un mensaje de error en caso de excepción
        System.out.println("Error al cargar los datos desde el archivo: " + e.getMessage());
    }
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void MOTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOTORActionPerformed

    private void FRENOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRENOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRENOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FRENO;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField MARCA;
    private javax.swing.JTextField MODELO;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JComboBox<String> MOTOR;
    private javax.swing.JComboBox<String> PINTAR;
    private javax.swing.JTextField PLACA;
    private javax.swing.JRadioButton botones;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminartodo;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables




}
    
        
